services:
  product-service:
    build: ./product-services
    ports: 
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${PRODUCT_DB_HOST}
      DB_NAME: ${PRODUCT_DB_NAME}
      DB_USER: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      - product-db
  
  product-db:
    image: mysql:8.0.36
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD : ${PRODUCT_DB_PASSWORD}
      MYSQL_DATABASE : ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql
  
  # cart-service:
  #   build: ./cart-services
  #   ports:
  #     - "8000:8000"
  #   container_name: cart-services
  #   restart: always

  # review-service:
  #   build: ./review-services
  #   ports:
  #     - "5002:5002"
  #   container_name: review-services
  #   restart: always

volumes:
  product-db-data:
  
  